// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEdxDhle3NruQmTkONKZ9icHRZpeHCbsA',
    appId: '1:813388236866:web:667a3e05e305debf19c5db',
    messagingSenderId: '813388236866',
    projectId: 'egycal',
    authDomain: 'egycal.firebaseapp.com',
    storageBucket: 'egycal.firebasestorage.app',
    measurementId: 'G-VNKXQ7HP8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB_Xa3nrqrvum48BynHRrHT_b2TcKrNMU',
    appId: '1:813388236866:android:8a1d9512706956aa19c5db',
    messagingSenderId: '813388236866',
    projectId: 'egycal',
    storageBucket: 'egycal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDExKoe6G8FOU0Kie_gqy4xQQBPO3fCnU4',
    appId: '1:813388236866:ios:8f4bbce5586dc21119c5db',
    messagingSenderId: '813388236866',
    projectId: 'egycal',
    storageBucket: 'egycal.firebasestorage.app',
    iosBundleId: 'com.example.egycal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDExKoe6G8FOU0Kie_gqy4xQQBPO3fCnU4',
    appId: '1:813388236866:ios:8f4bbce5586dc21119c5db',
    messagingSenderId: '813388236866',
    projectId: 'egycal',
    storageBucket: 'egycal.firebasestorage.app',
    iosBundleId: 'com.example.egycal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEdxDhle3NruQmTkONKZ9icHRZpeHCbsA',
    appId: '1:813388236866:web:514cfa4050525e2119c5db',
    messagingSenderId: '813388236866',
    projectId: 'egycal',
    authDomain: 'egycal.firebaseapp.com',
    storageBucket: 'egycal.firebasestorage.app',
    measurementId: 'G-QKBCBTYTPG',
  );
}
